### ISSUE TITLE
Error: local variable 'out_img' referenced before assignment

### ISSUE THREAD

**Issue by HelpSeeker** [iperov/OpenDeepFaceSwap#20]
I restarted training on Fedora 27 after the last commit and wanted to do some test converts. However I always get the following error message:
```
Collecting alignments: 100%|████████████████| 420/420 [00:00<00:00, 2702.77it/s]
Converting:   0%|                                       | 0/420 [00:00<?, ?it/s]
Error: local variable 'out_img' referenced before assignment
Traceback (most recent call last):
  File "/home/bla/src/OpenDeepFaceSwap/mainscripts/Converter.py", line 75, in main
    image = converter.convert(image, image_landmarks, model.is_debug())
  File "/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py", line 181, in convert
    return debugs if debug else out_img
UnboundLocalError: local variable 'out_img' referenced before assignment
```
This happens for all --mode options, while using the LIAEF128/MIAEF128 model (haven't trained the other ones). I also tried using --debug, which leads to this error message:
```
Collecting alignments: 100%|████████████████| 420/420 [00:00<00:00, 2714.29it/s]
Converting:   0%|                                       | 0/420 [00:00<?, ?it/s]
Error: local variable 'out_img' referenced before assignment
Traceback (most recent call last):
  File "/home/bla/src/OpenDeepFaceSwap/mainscripts/Converter.py", line 75, in main
    image = converter.convert(image, image_landmarks, model.is_debug())
  File "/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py", line 179, in convert
    debugs += [out_img.copy()]
UnboundLocalError: local variable 'out_img' referenced before assignment
```

**Comment by iperov** [comment]
check last commit

**Comment by HelpSeeker** [comment]
It starts now, but it throws errors while converting. Again I tested MIAEF128/LIAEF128 with all --mode options.

MIAEF128+hist-match-bw / LIAEF128+hist-match: No errors

MIAEF128+hist-match / LIAEF128+hist-match-bw:
```
Collecting alignments: 100%|████████████████| 420/420 [00:00<00:00, 2718.04it/s]
Converting:   1%|▎                              | 4/420 [00:02<04:06,  1.69it/s]
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:174: RuntimeWarning: invalid value encountered in multiply
  out_img = out_img * img_prd_border_rect_mask_a + img_bgr * (1.0 - img_prd_border_rect_mask_a)
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:174: RuntimeWarning: invalid value encountered in subtract
  out_img = out_img * img_prd_border_rect_mask_a + img_bgr * (1.0 - img_prd_border_rect_mask_a)
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:175: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_border_rect_mask_a
Converting:  21%|██████▎                       | 89/420 [00:14<00:55,  5.99it/s]
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:174: RuntimeWarning: invalid value encountered in add
  out_img = out_img * img_prd_border_rect_mask_a + img_bgr * (1.0 - img_prd_border_rect_mask_a)
Converting: 100%|█████████████████████████████| 420/420 [01:02<00:00,  6.77it/s]
```

MIAEF128/LIAEF128 + seamless:
```
Collecting alignments: 100%|████████████████| 420/420 [00:00<00:00, 2669.96it/s]
Converting:   1%|▏                              | 3/420 [00:03<07:33,  1.09s/it]
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:174: RuntimeWarning: invalid value encountered in multiply
  out_img = out_img * img_prd_border_rect_mask_a + img_bgr * (1.0 - img_prd_border_rect_mask_a)
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:174: RuntimeWarning: invalid value encountered in subtract
  out_img = out_img * img_prd_border_rect_mask_a + img_bgr * (1.0 - img_prd_border_rect_mask_a)
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:175: RuntimeWarning: invalid value encountered in multiply
  img_mask_blurry_aaa *= img_prd_border_rect_mask_a
Converting:   7%|██                            | 29/420 [00:28<06:24,  1.02it/s]
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:177: RuntimeWarning: overflow encountered in multiply
  out_img =  np.clip( img_bgr*(1-img_mask_blurry_aaa) + (out_img*img_mask_blurry_aaa) , 0, 1.0 )
Converting:  59%|█████████████████▏           | 249/420 [03:30<02:24,  1.18it/s]
/home/bla/src/OpenDeepFaceSwap/models/ConverterMasked.py:174: RuntimeWarning: invalid value encountered in add
  out_img = out_img * img_prd_border_rect_mask_a + img_bgr * (1.0 - img_prd_border_rect_mask_a)
Converting: 100%|█████████████████████████████| 420/420 [05:46<00:00,  1.21it/s]
```

All combinations only converted a few frames and otherwise copied the original images. During debug mode, it shows me the mask, but skips to the next frame instead of showing me the generated face. Additionally --mode seamless introduces black dots all over the image. Here's a snippet from such a picture (can't post the full thing, since it's NSFW):
![black_dots](https://user-images.githubusercontent.com/36918959/39494612-56e70ff2-4d97-11e8-8aee-da3fd916dbac.png)

**Comment by iperov** [comment]
because your frames have no mask

**Comment by iperov** [comment]
looks like you didnt remove bad aligned images and trained their crap mask

**Comment by iperov** [comment]
can you upload your workspace to google drive ?

**Comment by iperov** [comment]
I will fix it faster if you upload mode, both aligned folder, and dst original frames

**Comment by gessyoo** [comment]
iperov, I'm getting the same error, "UnboundLocalError local variable 'out_img' referenced before assignment" during the convert stage.  It completes about 1% and throws the error message.
I used the latest commit, deleting the old encoder, decoder and .dat files and starting training over from scratch.  Before training, I ran extract with the --mt option on about 5,000 src and dst images, and sorted and cleaned the blurry, black and inverted images before training.  I trained with the Dfaker model to about 0.18 loss on both sets of images.  I tried to convert with and without the hist-match and blur-match modifier, but got the same error message.   I'm running Win 10 x64, Anaconda 3.6, GTX 1070,  TF 1.8 and CUDA 9.0.  The latest code works fine for extraction and training, but the conversion gets stuck.  Thanks for your work on this.

**Comment by gessyoo** [comment]
Update, the latest fixed code works for conversion.

**Comment by HelpSeeker** [comment]
And I don't expect you to. When I talk about the results being ok or not, I just comment on whether the converted area covers the original face or is too small/large. If I can fix the hist-match modes by using custom blur/kernel size settings, then so be it.

My only remaining problem is, that the seamless mode is right now useless to me, as it introduces those black dots (and now also bars) to the converted pictures. Something that never happened in the last 16 test videos - for which I used the same training data and also the seamless mode - before the last big commit.

**Comment by HelpSeeker** [comment]
Upload is finally done.
https://drive.google.com/open?id=1iznU1nUAvI3HEvyf-bXJn6CPKwBUcdHx

**Comment by iperov** [comment]
why you didnt store it in one single zip file ?
now google stuck on preparing for download

**Comment by iperov** [comment]
downloaded
checking...

**Comment by iperov** [comment]
both models with both converting mode went fine without errors
![cmd_2018-05-03_16-27-05](https://user-images.githubusercontent.com/8076202/39576519-731dd12a-4eef-11e8-924b-9b7ba1dbaa36.jpg)

**Comment by iperov** [comment]
crap mask at LIAEF128 will be fixed
![python_2018-05-03_16-34-50](https://user-images.githubusercontent.com/8076202/39576677-06e0f590-4ef0-11e8-8816-aef1a2abe835.jpg)
->
![python_2018-05-03_16-35-25](https://user-images.githubusercontent.com/8076202/39576681-0a5aab30-4ef0-11e8-97ba-31b699bab7e7.jpg)

**Comment by HelpSeeker** [comment]
I still don't know what the problem is, but if anyone experiences the same thing: 
Try the H64/H128 model. They convert without any errors.

**Comment by iperov** [comment]
HelpSeeker can you provide teamviewer access to your comp?
