### ISSUE TITLE
libpng error: bad adaptive filter value

### ISSUE THREAD

**Issue by johnc2k** [iperov/OpenDeepFaceSwap#31]
Using Release: OpenDeepFaceSwap_build_08_05_2018.zip (torrent)
I received the following error message whilst training "LIAEF128 best GPU":

```
Saving...[#028748][1180ms] loss_src: 0.01021 loss_dst: 0.00872
Saving...[#029061][1219ms] loss_src: 0.01061 loss_dst: 0.00872
libpng error: bad adaptive filter value01065 loss_dst: 0.00813
Process Process-1:
Traceback (most recent call last):
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\TrainingDataGeneratorBase.py", line 79, in batch_func
    x = self.onProcessSample (sample, self.debug)
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\FullFaceTrainingDataGenerator.py", line 43, in onProcessSample
    d_image = target_sample.load_image()
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\BaseTypes.py", line 39, in load_image
    img = cv2.imread (self.filename).astype(np.float32) / 255.0
AttributeError: 'NoneType' object has no attribute 'astype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 252, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\utils\iter_utils.py", line 37, in process_func
    gen_data = next (self.generator_func)
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\TrainingDataGeneratorBase.py", line 81, in batch_func
    raise Exception ("Exception occured in sample %s. Error: %s" % (sample.filename, traceback.format_exc() ) )
Exception: Exception occured in sample D:\OpenDeepFaceSwapTorrent\workspace\data_src\aligned\00264.png. Error: Traceback (most recent call last):
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\TrainingDataGeneratorBase.py", line 79, in batch_func
    x = self.onProcessSample (sample, self.debug)
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\FullFaceTrainingDataGenerator.py", line 43, in onProcessSample
    d_image = target_sample.load_image()
  File "D:\OpenDeepFaceSwapTorrent\_internal\bin\OpenDeepFaceSwap\models\BaseTypes.py", line 39, in load_image
    img = cv2.imread (self.filename).astype(np.float32) / 255.0
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by iperov** [comment]
check image D:\OpenDeepFaceSwapTorrent\workspace\data_src\aligned\00264.png
may be it corrupted

**Comment by iperov** [comment]
and upload your workspace, I will check

**Comment by iperov** [comment]
no response from author
