### ISSUE TITLE
Further enhancing model.

### ISSUE THREAD

**Issue by iperov** [iperov/OpenDeepFaceSwap#32]
I found that residual layer decoding 128 from 64 proposed by DF is suxx. It just imagines 2x2 from 1x1 which result some jitter https://www.youtube.com/watch?v=lv0v4Pbyk_o

Match warper proposed by DF also gives no significant differences. So I return it to grid random warper.

IAE Intermediate 8x8 code better than 4x4, but eats more ram.

Grid random warper better with gaussian distribution than uniform (current).

TensorFlow 1.8.0 contains better SSIM loss.

I will post stunning comparison cage-trump video soon.

**Comment by iperov** [comment]
![liaef128_cage_0](https://user-images.githubusercontent.com/8076202/40036663-c38e0796-5819-11e8-80a6-380c043ec5aa.jpg)
https://www.youtube.com/watch?v=_52EaJi1USI

**Comment by ruah1984** [comment]
@iperov how you learn the voice??

**Comment by iperov** [comment]
@ruah1984 what you mean ?

**Comment by LordOEQJen** [comment]
Looks great. What gpu are you using btw ?

**Comment by iperov** [comment]
gtx1060 6gb

**Comment by ruah1984** [comment]
@iperov the video , the voice is cage , not trump. how you do this?

**Comment by iperov** [comment]
@ruah1984 lol no, original voice of Trump

**Comment by kidol** [comment]
You still use 64x64?

**Comment by iperov** [comment]
@kidol no i dont. 64x64 just for demo and for 2GB cards.

**Comment by licolane** [comment]
It looks awesome. There are visible improvements. I look forward to testing

**Comment by LordOEQJen** [comment]
I tested H128 model the past days (gtx 970). It needs much more time than original Trainer from faceswap repo (as expected before), but it has definitely good benefit in Details. Especially eyes and teeth area looks much better.

**Comment by frosty3907** [comment]
looking forward to win exe!

**Comment by loldfdfdf** [comment]
The eyes look great!

When can we have new models and code to test?

**Comment by iperov** [comment]
I pushed commit. But windows binary not ready yet

**Comment by Kirin-kun** [comment]
I'll test H128 when you commit.

I've been trying some new facesets and I often have problems with eyes closed/mouth open because when there's more closed eyes than open in src, I end up with half open eyes on dest and it looks creepy. same thing for mouth.

**Comment by iperov** [comment]
converter now produces 15 fps even with seamless mode

**Comment by iperov** [comment]
windows binray ready https://rutracker.org/forum/viewtopic.php?p=75360801

**Comment by LordOEQJen** [comment]
Will definitely give it a try today

**Comment by gessyoo** [comment]
Very impressive results, will be testing models today.

**Comment by iperov** [comment]
@Kirin-kun how many VRAM in your videocard ?

**Comment by Kirin-kun** [comment]
It's a GTX 1060 6Gb, same as yours.

I'm currently training a faceset and it's looking good in the preview at around 10.000 epochs. I'll try to convert when it's less blurry. Loss looks like this:

![image](https://user-images.githubusercontent.com/36699120/40174595-e66b99dc-59d5-11e8-96a8-0293a0a2c9a2.png)

I think the problem with half open eyes in my previous faceset came from the eyelashes/make-up.

When with closed eyes, it makes a dark line and probably the model predicts it as half closed instead of closed. Not all faceswaps can be successful.

**Comment by iperov** [comment]
I found that 256 bottleneck cannot learn closed eyes in LIAEF128 model
H128 has 512 bottleneck.
Also closed eyes learned between ~20000-50000 epochs.

**Comment by Sonofdemoc** [comment]
Hi, I tried new H128. faster but the problem Kirin-kun said(about eye learning) still exists after ~45000 epoch.

like this


![image](https://user-images.githubusercontent.com/19576122/40176255-c25c107c-5a15-11e8-84ba-a3e89f1ede46.png)

![image](https://user-images.githubusercontent.com/19576122/40176477-78023e24-5a16-11e8-8b9a-3ebd04582670.png)

![image](https://user-images.githubusercontent.com/19576122/40176487-824318d6-5a16-11e8-8e95-a0654ce74a1a.png)

**Comment by iperov** [comment]
@Sonofdemoc there is no eyes problem in your example

**Comment by Sonofdemoc** [comment]
Oh, an Asian face can be hard to recognize for you. Dst_face is half-closed or mostly closed, but the converted result is opening its eyes. That's the problem. If it's hard to understand, I'll give you a clearer example. Wait for me

**Comment by Kirin-kun** [comment]
At least, on the second couple of images, src has eyes closed but dst has eyes half-closed, and is even cross-eyed.

**Comment by Kirin-kun** [comment]
I'm currently training two caucasian faces and the problem with eyes isn't showing much, unlike my previous faceset, where src was asian.

Maybe the model is having troubles with asian eyes, because landmarks don't differ enough between open and closed.

**Comment by iperov** [comment]
@Sonofdemoc in your last example I see that all is fine. Model works properly.

**Comment by iperov** [comment]
just find more detailes src faces. Remove blurry faces. Add src faces with opened eyes, so NN will better recognize closed eyes.

**Comment by Sonofdemoc** [comment]
Hmm. I think it has nothing to do with src data. I'm using src_data already proven in faceswap. 500-1000pic with no blurry. many expression. diverse angles.

**Comment by LordOEQJen** [comment]
Just mentioned for @Sonofdemoc for the case, that face-detection doesn't work for (his) asian faces.

**Comment by Kirin-kun** [comment]
@iperov I actually deinstalled bloated anaconda 3 and switched to simple python. 

However, I still had problems with suppress std. It stopped before starting to train.

With latest commit, it's a lot better, it doesn't output usual warning about deprecation, etc..

But, as training starts, I still have the warning about memory:

```
C:\Users\Kirin\face>python c:\users\kirin\face\opendeepfaceswap\main.py --tf-sup
press-std train --training-data-src-dir H:\Fakes\00SRC_DATA\aligned.ip --trainin
g-data-dst-dir H:\Fakes\gamer\aligned.ip --model-dir h:\fakes\modeli.00SRC_DATA.
gamer --model H128 --batch-size 16
Running trainer.

Loading model...
Loading: 100%|██████████████████████████████| 490/490 [00:01<00:00, 249.60it/s]
Loading: 100%|████████████████████████████| 1988/1988 [00:10<00:00, 193.98it/s]
===== Model summary =====
== Model name: H128
==
== Current epoch: 30342
==
== Options:
== |== batch_size : 16
== |== multi_gpu : False
== |== created_vram_gb : 6.0
== Running on:
== |== [0 : GeForce GTX 1060 6GB]
=========================
Starting. Press "Enter" to stop training and save model.
2018-05-17 22:10:06.541686: W T:\src\github\tensorflow\tensorflow\core\common_ru
ntime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to al
locate 3.13GiB. The caller indicates that this is not a failure, but may mean th
at there could be performance gains if more memory were available.
Training [#030473][1512ms] loss_src: 0.08952 loss_dst: 0.04626
```

**Comment by Sonofdemoc** [comment]
Another training (with faceswap converted example)

example A
![image](https://user-images.githubusercontent.com/19576122/40206933-fef6cf0c-5a6c-11e8-9d50-6dad91d71f01.png)
example B
![image](https://user-images.githubusercontent.com/19576122/40207158-08ebaab8-5a6e-11e8-9300-4db5fb054c91.png)
example C
![image](https://user-images.githubusercontent.com/19576122/40207284-bba92f36-5a6e-11e8-9be5-3eac2da5660d.png)

1. dst_face 2. faceswap 3. H128 50,000 epoch 4. H128 70,000 epoch

A,B In short, H128 converted eyes are too large and not too clear.
C is not bad. But look at the far right, you can see that she's trying to open her eyes.
After 50,000 epoch. It doesn't get better, it gets worse.

**Comment by Sonofdemoc** [comment]
@iperov  faceswap repo is not making any progress(no fun), and your ideas are fascinating. So it's always fun to test your model. I look forward to the next update.

**Comment by iperov** [comment]
@Kirin-kun 
> But, as training starts, I still have the warning about memory:
it is fine, because I didnt supress training output

**Comment by Kirin-kun** [comment]
H128 gives grayish/blurry pupils, even when it's only trying to redraw src or dst. It gives the impression of "empty eyes". It's even visible on your Trump/Cage example up there: Cage has blurry eyes;

Maybe it's because of the averaging. 

Same thing for cross-eyed faces: if in lots of src faces the subject shifts their gaze to left or right instead of looking straight at the camera, eyes are learned *independently* and it gives strabismus, like the face on the right in example B of @Sonofdemoc .

It's less pregnant in faceswap. I don't know if it comes from going to 128 or from your model.

**Comment by iperov** [comment]
I dont know what to change for asian faces :D

**Comment by iperov** [comment]
of course some experiments can be applied, but it will take a weeks

**Comment by Kirin-kun** [comment]
I wonder if there's a way to learn gaze direction. Like the GAN model is supposed to, with perceptual loss.

**Comment by iperov** [comment]
GAN ? I got zero acceptable results with gan.
May ban only for asian faces I dont know.

**Comment by iperov** [comment]
if you want test some, change TrainingDataGenerator.py to this:
```
from facelib import FaceType
from facelib import LandmarksProcessor
import cv2
import numpy as np
from models import TrainingDataGeneratorBase
from utils import image_utils
from utils import random_utils
from enum import IntEnum
'''
generates full face images 
    random_flip 
    output_sample_types_flags is TrainingDataGenerator.SampleTypeFlags
'''   
class TrainingDataGenerator(TrainingDataGeneratorBase):
    class SampleTypeFlags(IntEnum):
        WARPED               = 0x00001,
        TARGET               = 0x00002,
        TARGET_UNTRANSFORMED = 0x00004,
        
        HALF_FACE   = 0x00010,
        FULL_FACE   = 0x00020,
        HEAD_FACE   = 0x00040,
        AVATAR_FACE = 0x00080,
        
        MODE_BGR  = 0x00100,  #BGR
        MODE_G    = 0x00200,  #Grayscale
        MODE_GGG  = 0x00400,  #3xGrayscale 
        MODE_M    = 0x00800,  #mask only    
        MODE_BGRM = 0x01000,  #BGR + mask
        MODE_GM   = 0x02000,  #Grayscale + mask
        MODE_GGGM = 0x04000,  #3xGrayscale + mask            
        
        SIZE_64   = 0x10000,
        SIZE_128  = 0x20000,
        SIZE_256  = 0x40000,
        
    #overrided
    def onInitialize(self, random_flip=False, output_sample_types_flags=[], **kwargs):
        self.random_flip = random_flip        
        self.output_sample_types_flags = output_sample_types_flags
        
    #overrided
    def onProcessSample(self, sample, debug):
        s_bgrm = sample.load_bgrm()

        if debug:
            LandmarksProcessor.draw_landmarks (s_bgrm, sample.landmarks, (0, 1, 0))

        warped_bgrm, target_bgrm, target_bgrm_untransformed = TrainingDataGenerator.warp (s_bgrm, sample.landmarks)

        if self.random_flip and np.random.randint(10) < 4:
            warped_bgrm = warped_bgrm[:,::-1,:]
            target_bgrm = target_bgrm[:,::-1,:]
            target_bgrm_untransformed = target_bgrm[:,::-1,:]

        outputs = []
        
        for t in self.output_sample_types_flags:
            if t & self.SampleTypeFlags.WARPED != 0:
                source = warped_bgrm
            elif t & self.SampleTypeFlags.TARGET != 0:
                source = target_bgrm
            elif t & self.SampleTypeFlags.TARGET_UNTRANSFORMED != 0:
                source = target_bgrm_untransformed
            else:
                raise ValueError ('expected SampleTypeFlags warped/target type')

            if t & self.SampleTypeFlags.SIZE_64 != 0:
                size = 64
            elif t & self.SampleTypeFlags.SIZE_128 != 0:
                size = 128
            elif t & self.SampleTypeFlags.SIZE_256 != 0:
                size = 256
            else:
                raise ValueError ('expected SampleTypeFlags size')
                
            if t & self.SampleTypeFlags.HALF_FACE != 0:
                target_face_type = FaceType.HALF            
            elif t & self.SampleTypeFlags.FULL_FACE != 0:
                target_face_type = FaceType.FULL
            elif t & self.SampleTypeFlags.HEAD_FACE != 0:
                target_face_type = FaceType.HEAD
            elif t & self.SampleTypeFlags.AVATAR_FACE != 0:
                target_face_type = FaceType.AVATAR
            else:
                raise ValueError ('expected SampleTypeFlags face type')
                
            if target_face_type > sample.face_type:
                raise Exception ('sample %s type %s does not match model requirement %s. Consider extract necessary type of faces.' % (sample.filename, sample.face_type, target_face_type) )

            source = cv2.warpAffine( source, LandmarksProcessor.get_transform_mat (sample.landmarks, size, target_face_type), (size,size), flags=cv2.INTER_LANCZOS4 )
 
            if t & self.SampleTypeFlags.MODE_BGR != 0:
                source = source[...,0:3]
            elif t & self.SampleTypeFlags.MODE_G != 0:
                source = np.expand_dims(cv2.cvtColor(source[...,0:3], cv2.COLOR_BGR2GRAY),-1)
            elif t & self.SampleTypeFlags.MODE_GGG != 0:
                source = np.repeat ( np.expand_dims(cv2.cvtColor(source[...,0:3], cv2.COLOR_BGR2GRAY),-1), (3,), -1)
            elif t & self.SampleTypeFlags.MODE_BGRM != 0:
                source = source
            elif t & self.SampleTypeFlags.MODE_GM != 0:
                source = np.concatenate( ( np.expand_dims(cv2.cvtColor(source[...,0:3], cv2.COLOR_BGR2GRAY),-1),
                                           np.expand_dims(source[...,-1],-1)
                                         )
                                         , -1
                                       )
            elif t & self.SampleTypeFlags.MODE_GGGM != 0:
                source = np.concatenate( ( np.repeat ( np.expand_dims(cv2.cvtColor(source[...,0:3], cv2.COLOR_BGR2GRAY),-1), (3,), -1),
                                           np.expand_dims(source[...,-1],-1)
                                         )
                                         , -1
                                       )
            elif t & self.SampleTypeFlags.MODE_M != 0:
                source = np.expand_dims(source[...,-1],-1)
            else:
                raise ValueError ('expected SampleTypeFlags mode')
                
            outputs.append ( source )

        if debug:
            result = (s_bgrm,)

            for output in outputs:
                if output.shape[2] < 4:
                    result += (output,)
                elif output.shape[2] == 4:
                    result += ( output[...,0:-1]*np.expand_dims(output[...,-1],-1), )

            return result            
        else:
            return outputs
            
    @staticmethod
    def warp(image_bgrm, s_landmarks):          
        h,w,c = image_bgrm.shape
        if (h != w) or (w != 64 and w != 128 and w != 256 and w != 512 and w != 1024):
            raise ValueError ('TrainingDataGenerator accepts only square power of 2 images.')
            
        rotation = np.random.uniform(-10, 10)
        scale = np.random.uniform(1 - 0.05, 1 + 0.05)
        tx = np.random.uniform(-0.05, 0.05)
        ty = np.random.uniform(-0.05, 0.05)    
     
        #random warp by grid
        cell_size = 64
        cell_count = w // cell_size + 1
        
        grid_points = np.linspace( 0, w, cell_count)
        mapx = np.broadcast_to(grid_points, (cell_count, cell_count)).copy()
        mapy = mapx.T
        
        mapx[1:-1,1:-1] = mapx[1:-1,1:-1] + random_utils.random_normal( size=(cell_count-2, cell_count-2) )*(cell_size*0.24)
        mapy[1:-1,1:-1] = mapy[1:-1,1:-1] + random_utils.random_normal( size=(cell_count-2, cell_count-2) )*(cell_size*0.24)

        half_cell_size = cell_size // 2
        
        mapx = cv2.resize(mapx, (w+cell_size,)*2 )[half_cell_size:-half_cell_size-1,half_cell_size:-half_cell_size-1].astype(np.float32)
        mapy = cv2.resize(mapy, (w+cell_size,)*2 )[half_cell_size:-half_cell_size-1,half_cell_size:-half_cell_size-1].astype(np.float32)
        warped_bgrm = cv2.remap(image_bgrm, mapx, mapy, cv2.INTER_LANCZOS4 )
        
        #random transform                                   
        random_transform_mat = cv2.getRotationMatrix2D((w // 2, w // 2), rotation, scale)
        random_transform_mat[:, 2] += (tx*w, ty*w)

        warped_bgrm = cv2.warpAffine( warped_bgrm, random_transform_mat, (w, w), borderMode=cv2.BORDER_CONSTANT, flags=cv2.INTER_LANCZOS4 )
        target_bgrm = cv2.warpAffine( image_bgrm , random_transform_mat, (w, w), borderMode=cv2.BORDER_CONSTANT, flags=cv2.INTER_LANCZOS4 )        
        
        return warped_bgrm, target_bgrm, image_bgrm

```

**Comment by iperov** [comment]
^ random flip changed to 40% change as faceswap
and grid warper changed to 4 points, instead of 8 points, as faceswap

**Comment by iperov** [comment]
If eyes still be not good,
then you can change H128 model.py

```
self.autoencoder_src.compile(optimizer=optimizer, loss=[DSSIMMaskLossClass(self.tf)(mask_layer), 'mae'])
self.autoencoder_dst.compile(optimizer=optimizer, loss=[DSSIMMaskLossClass(self.tf)(mask_layer), 'mae'])
```

to

```
self.autoencoder_src.compile(optimizer=optimizer, loss=['mae', 'mae'])
self.autoencoder_dst.compile(optimizer=optimizer, loss=['mae', 'mae'])
```

this removes DSSIM loss func to regular mae as faceswap

**Comment by iperov** [comment]
@Kirin-kun can you upload your workspace with last asian faces? I will check some changes

**Comment by ruah1984** [comment]
@kidol can you share the result ?

**Comment by kidol** [comment]
@ruah1984 I created this back in the /r/deepfakes days: https://mega.nz/#!tlsH2KzI!RgTKKu-VSOQNWlxE3ubVIZUQrZLeyvvGJKsBDYuhv1A
If you give me your reddit username, I send you a different video which shows quality better.

**Comment by ruah1984** [comment]
@kidol san, reddit username same as the name here. May I know if the model from GAN can reuse back for other fAce ?

**Comment by kidol** [comment]
@ruah1984 With reuse you mean use trained model and continue training with different face? Yes it works pretty well. I send you video.

**Comment by LordOEQJen** [comment]
![iifidie243](https://user-images.githubusercontent.com/39125942/40238848-af9e8966-5ab4-11e8-84fc-674080bc0f7f.png)

Can confirm that eye problem on H128 on a few frames

**Comment by Sonofdemoc** [comment]
> ^ random flip changed to 40% as faceswap
> and grid warper changed to 4 points, instead of 8 points, as faceswap

I tested it and it made the situation worse. Eye problems remain and there are new additions. It makes both sides of the face same.

![image](https://user-images.githubusercontent.com/19576122/40261293-baf6f376-5b3a-11e8-8385-e62594a6a840.png)

 H64_20,000 epoch 

Mae is also irrelevant. Because the problem with eyes already existed when the mae was used.

**Comment by iperov** [comment]
no eyes problem
Problem in son of bitch.

@Sonofdemoc you fooled me.

relating to this issue https://github.com/iperov/OpenDeepFaceSwap/issues/22

You told you got this result in face swap:
![39529765-692e5a82-4e62-11e8-9569-b3f3ca32239a 1](https://user-images.githubusercontent.com/8076202/40264344-4bcc0c1e-5b32-11e8-8421-0925fddad294.png)

And this result of H64 you claimed as weird eyes:
![39529784-76736b2e-4e62-11e8-95ec-d840c99ebd2d 1](https://user-images.githubusercontent.com/8076202/40264351-8c240712-5b32-11e8-9b4f-84ed76d5baee.png)

**I trained your faceset on face swap to check.**
And what I got:
![000074_0 faceswap](https://user-images.githubusercontent.com/8076202/40264367-ec27db20-5b32-11e8-8aa0-46382a084eb9.png)

WTF @Sonofdemoc  ????

You spent huge amount of time to nothing.
Go away from this repo.

**Comment by Goatmeal412** [comment]
@iperov It sounds silly. Why should I deceive you? for what? if it's not a faceswap, where on earth did those results come from? And I am not alone reporting the problem. Are you going to ban everyone who says there's a problem?

I don't know what a fool this is.

You tell me to go away, so I'm off.

But what you're doing is a big mistake. Everyone watched this.

**Comment by iperov** [comment]
` Everyone watched this.`
I dont care.

**Comment by sonofdemoc2** [comment]
It sounds silly. Why should I deceive you? for what? if it's not a face-swap, where on earth did those results come from? And I am not alone reporting the problem. Are you going to ban everyone who says there's a problem?

I don't know what a fool this is.

You tell me to go away, so I'm off.

But what you're doing is a big mistake. Everyone watched this.

-------------------------------------------------------------------------------------------------

@iperov Even censorship? you made it up. I can put my workspace up again and when people test it, they know you're lying. You can't erase this. people will know.

**Comment by iperov** [comment]
42k epochs from latest commit:
![000074_0 last](https://user-images.githubusercontent.com/8076202/40267914-d46a2810-5b75-11e8-97fb-8950c8adbbea.png)

**Comment by frosty3907** [comment]
Guys we don't need this kind of drama. Reel it in.

**Comment by iperov** [comment]
I found that 1 batch size prevents 2GB model from recognizing closed eyes, even on 110k epochs.

**Comment by gessyoo** [comment]
iperov , I'm testing the latest code, eye recognition is better even at 5k epochs,  Here are open, closed and half-closed eyes.  https://ibb.co/n26rO8.  Reading (google translated to English) discussion on https://rutracker.org/forum/viewtopic.php?p=75318742, I tried batch size 32 on 8 Gb. GTX1070.  I wanted to try adjusting Dense as suggested, but my python skills are weak.

**Comment by iperov** [comment]
hm then it depends on face. Thx for preview.

**Comment by gessyoo** [comment]
Now testing your MIAEF256 model, works on GTX 1070 with batch size 8; added
      if self.gpu_total_vram_gb == 8:
         self.batch_size = 8
Will convert still work with MIAEF256, or is this model just for test now?

**Comment by kidol** [comment]
@iperov Do you think it makes any sense to use YUV format as input instead of RGB? This could result in two networks: One for details (Y channel) and one for color (UV channels). This has benefit that one can train each network on each own (more VRAM for each network?). Also the color network might be reusable even if main network changes in terms of network size, training methods, etc.

**Comment by lewddev** [comment]
Is it possible to add kerras-vggface perceptual loss (as using in faceswap-GAN) to improve result?

**Comment by iperov** [comment]
this is pointless

**Comment by iperov** [comment]
I never got any acceptable result with faceswap-GAN.

**Comment by room3dev** [comment]
sorry, I mean adding vggface's perceptual loss as part of loss function of H128 model.

**Comment by room3dev** [comment]
sorry, I mean adding vggface's perceptual loss as one part of loss function in H128 model.

**Comment by lewddev** [comment]
Sorry, I mean adding vggface perceptual loss as another part of loss function in H128 model.

**Comment by iperov** [comment]
as I said this is pointless

**Comment by lewddev** [comment]
I think LSGAN alone (without occlusion masking) from FaceSwap_GAN_v2_sz128 is good enough for reconstruct face task. here the result I got (no occlusion masking here)
![lsgan-no-masking](https://user-images.githubusercontent.com/39359850/40641649-93a18b4e-6344-11e8-93f7-5caebdebdf92.jpg)

**Comment by iperov** [comment]
do you know how conv nets and autoencoders works? Do you know what VGG Face Net actually do ?

**Comment by lewddev** [comment]
I don't know, I have very little knowledge about neural networks that why I ask you for help.
I really sorry if I made you upset, I don't mean it.

**Comment by gessyoo** [comment]
iperov, here is a sample of Audrey Hepburn's face replacing Jennifer Love Hewlett's.  http://sendvid.com/loexmyyd.  The eyes opening and closing look good to me, there were open and closed eye images in both training sets.  Used Model_MIAEF128, 65,000 epochs, and about 1,400 images in each data set. I ended preferring hist-match with masked convert result after comparing seamless hist-match results, because of less pronounced color artifacts.  I'm not sure what caused the color artifact dots, the conversion seems to pick up the background colors at times, or maybe there is too much color variation in the data set images.

**Comment by iperov** [comment]
this can be fixed by manual extracting dst faces and prevent mask offseting
![chrome_2018-06-02_21-52-41](https://user-images.githubusercontent.com/8076202/40879326-47b11f56-66af-11e8-98c5-7035569650a5.jpg)

**Comment by gessyoo** [comment]
Thanks, will try manual extract.

**Comment by iperov** [comment]
you can update it manually

**Comment by blanky451** [comment]
I have, and I've modified some of the batch files for that purpose, but I'm having trouble with conversion. When I go to convert, I get this error:

> Exception while process data [undefined]: Traceback (most recent call last):
  File "C:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 232, in subprocess
    result = self.onClientProcessData (data)
  File "C:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Converter.py", line 150, in onClientProcessData
    image = self.converter.convert_image(image, image_landmarks, self.debug)
  File "C:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\models\Model_AVATAR\Model.py", line 214, in convert_image
    face_mat            = LandmarksProcessor.get_transform_mat (img_face_landmarks, self.predictor_input_size, face_type=FaceType.HALF )
  File "C:\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\LandmarksProcessor.py", line 58, in get_transform_mat
    mat = umeyama(image_landmarks[17:], landmarks_2D, True)[0:2]
IndexError: too many indices for array <

Any ideas as to what I'm doing wrong?

**Comment by iperov** [comment]
converter --input-dir contains **aligned** dst faces in sequence to be converted, its mean you can train on 1500 dst faces, but use only 100 for convert.
