### ISSUE TITLE
Could batch size be added to conversion to help with memory errors?

### ISSUE THREAD

**Issue by wackyphillwillis** [iperov/OpenDeepFaceSwap#39]
I get out of memory errors during conversion if my input images are large ~5400x2700. Can anything be done to lower the memory requirements of a conversion run using H128?

**Comment by wackyphillwillis** [comment]
I deleted my test case. I'll try again a later and post the exact memory allocation errors.

**Comment by wackyphillwillis** [comment]
Windows 10 16GB
GeForce GTX 1080Ti 11GB

Here's the error:

penCV Error: Unspecified error (The numpy array of typenum=11, ndims=3 can not be created) in NumpyAllocator::allocate, file C:\projects\opencv-python\opencv\modules\python\src2\cv2.cpp, line 181
OpenCV Error: Insufficient memory (Failed to allocate 174960000 bytes) in cv::OutOfMemoryError, file C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp, line 55
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Converter.py", line 166, in onClientProcessData
    image = self.converter.convert(image, image_landmarks, self.debug)
  File "e:\OpenDeepFaceSwap-master\models\ConverterMasked.py", line 94, in convert
    out_img = img_bgr.copy()
MemoryError
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Converter.py", line 166, in onClientProcessData
    image = self.converter.convert(image, image_landmarks, self.debug)
  File "e:\OpenDeepFaceSwap-master\models\ConverterMasked.py", line 116, in convert
    img_mask_blurry_aaa = cv2.erode(img_mask_blurry_aaa, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(ero,ero)), iterations = 1 )
cv2.error: C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp:55: error: (-4) Failed to allocate 174960000 bytes in function cv::OutOfMemoryError



OpenCV Error: Unspecified error (The numpy array of typenum=11, ndims=3 can not be created) in NumpyAllocator::allocate, file C:\projects\opencv-python\opencv\modules\python\src2\cv2.cpp, line 181
OpenCV Error: Insufficient memory (Failed to allocate 174960000 bytes) in cv::OutOfMemoryError, file C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp, line 55
OpenCV Error: Unspecified error (The numpy array of typenum=11, ndims=3 can not be created) in NumpyAllocator::allocate, file C:\projects\opencv-python\opencv\modules\python\src2\cv2.cpp, line 181
OpenCV Error: Insufficient memory (Failed to allocate 174960000 bytes) in cv::OutOfMemoryError, file C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp, line 55
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Converter.py", line 166, in onClientProcessData
    image = self.converter.convert(image, image_landmarks, self.debug)
  File "e:\OpenDeepFaceSwap-master\models\ConverterMasked.py", line 121, in convert
    img_mask_blurry_aaa = cv2.blur(img_mask_blurry_aaa, (blur, blur) )
cv2.error: C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp:55: error: (-4) Failed to allocate 174960000 bytes in function cv::OutOfMemoryError

Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Converter.py", line 166, in onClientProcessData
    image = self.converter.convert(image, image_landmarks, self.debug)
  File "e:\OpenDeepFaceSwap-master\models\ConverterMasked.py", line 121, in convert
    img_mask_blurry_aaa = cv2.blur(img_mask_blurry_aaa, (blur, blur) )
cv2.error: C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp:55: error: (-4) Failed to allocate 174960000 bytes in function cv::OutOfMemoryError



Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Converter.py", line 166, in onClientProcessData
    image = self.converter.convert(image, image_landmarks, self.debug)
  File "e:\OpenDeepFaceSwap-master\models\ConverterMasked.py", line 162, in convert
    out_img = np.clip( img_bgr*(1-img_face_mask_aaa) + (out_img*img_face_mask_aaa) , 0, 1.0 )
MemoryError

**Comment by iperov** [comment]
how many RAM you have? And swapfile size

**Comment by wackyphillwillis** [comment]
It's above 16GB system RAM. 11GB video RAM. Swap file max was like 10GB.

**Comment by iperov** [comment]
try swap file 50gb for test
