### ISSUE TITLE
Exception during extract

### ISSUE THREAD

**Issue by wackyphillwillis** [iperov/OpenDeepFaceSwap#43]
Error:
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Extractor.py", line 251, in onClientProcessData
    a_png = AlignedPNG.load (output_file)
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 242, in load
    chunk = chunk_map.get(chunk_name, Chunk).load(data[chunk_start:chunk_end])
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 32, in load
    inst.verify_crc()
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 60, in verify_crc
    raise ValueError(msg)
ValueError: CRC mismatch: 252111F3 (header), F747AF80 (calculated)
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Extractor.py", line 251, in onClientProcessData
    a_png = AlignedPNG.load (output_file)
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 242, in load
    chunk = chunk_map.get(chunk_name, Chunk).load(data[chunk_start:chunk_end])
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 32, in load
    inst.verify_crc()
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 60, in verify_crc
    raise ValueError(msg)
ValueError: CRC mismatch: 252111F3 (header), F747AF80 (calculated)
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Extractor.py", line 251, in onClientProcessData
    a_png = AlignedPNG.load (output_file)
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 242, in load
    chunk = chunk_map.get(chunk_name, Chunk).load(data[chunk_start:chunk_end])
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 32, in load
    inst.verify_crc()
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 60, in verify_crc
    raise ValueError(msg)
ValueError: CRC mismatch: 809B4E05 (header), 0FCCD3D7 (calculated)
Exception while process data: Traceback (most recent call last):
  File "e:\OpenDeepFaceSwap-master\utils\SubprocessorBase.py", line 227, in subprocess
    result = self.onClientProcessData (data)
  File "e:\OpenDeepFaceSwap-master\mainscripts\Extractor.py", line 251, in onClientProcessData
    a_png = AlignedPNG.load (output_file)
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 242, in load
    chunk = chunk_map.get(chunk_name, Chunk).load(data[chunk_start:chunk_end])
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 32, in load
    inst.verify_crc()
  File "e:\OpenDeepFaceSwap-master\utils\AlignedPNG.py", line 60, in verify_crc
    raise ValueError(msg)
ValueError: CRC mismatch: 8ED1B8C5 (header), BAE753C2 (calculated)

It would be nice if it specified which image was the troublesome one.

**Comment by iperov** [comment]
is this happens every time of extract?

**Comment by iperov** [comment]
if yes, then upload your frames, I will test it.

**Comment by wackyphillwillis** [comment]
Here's a batch of images that will consistently cause an error: https://www.filedropper.com/err_2

**Comment by iperov** [comment]
@wackyphillwillis check your url

**Comment by iperov** [comment]
fixed, check last commit
