### ISSUE TITLE
IAEF128 multi-gpu Error

### ISSUE THREAD

**Issue by shun115** [iperov/OpenDeepFaceSwap#5]
Hi Iperov,

I use multi GPU server.
I run `main.py train` with `--model IAEF128 --multi-gpu` option.
And error occurs:
```
2018-04-19 07:30:19.004817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0, 1, 2, 3
2018-04-19 07:30:20.240754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-19 07:30:20.240804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 1 2 3
2018-04-19 07:30:20.240812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N Y N N
2018-04-19 07:30:20.240825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   Y N N N
2018-04-19 07:30:20.240834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 2:   N N N Y
2018-04-19 07:30:20.240840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 3:   N N Y N
2018-04-19 07:30:20.241585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15054 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
2018-04-19 07:30:20.511644: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15133 MB memory) -> physical GPU (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:05.0, compute capability: 6.0)
2018-04-19 07:30:20.781932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 15133 MB memory) -> physical GPU (device: 2, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:06.0, compute capability: 6.0)
2018-04-19 07:30:21.052414: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 15133 MB memory) -> physical GPU (device: 3, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:07.0, compute capability: 6.0)
Error: ('The name "model_2" is used 2 times in the model. All layer names should be unique. Layer names: ', ['input_1', 'input_2', 'lambda_1', 'lambda_2', 'lambda_3', 'lambda_4', 'lambda_5', 'lambda_6', 'lambda_7', 'lambda_8', 'model_6', 'model_2', 'model_2'])
Traceback (most recent call last):
  File "/home/deployer/OpenDeepFaceSwap/mainscripts/Trainer.py", line 41, in trainerThread
    **in_options)
  File "/home/deployer/OpenDeepFaceSwap/models/ModelBase.py", line 115, in __init__
    self.onInitialize(**in_options)
  File "/home/deployer/OpenDeepFaceSwap/models/Model_IAEF128/Model.py", line 63, in onInitialize
    self.autoencoder_src = self.keras.utils.multi_gpu_model( self.autoencoder_src, self.gpu_idxs )
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/utils/multi_gpu_utils.py", line 189, in multi_gpu_model
    return Model(model.inputs, merged)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/deployer/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4204, in device
    yield
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/utils/multi_gpu_utils.py", line 189, in multi_gpu_model
    return Model(model.inputs, merged)
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 1829, in __init__
    'Layer names: ', all_names)
RuntimeError: ('The name "model_2" is used 2 times in the model. All layer names should be unique. Layer names: ', ['input_1', 'input_2', 'lambda_1', 'lambda_2', 'lambda_3', 'lambda_4', 'lambda_5', 'lambda_6', 'lambda_7', 'lambda_8', 'model_6', 'model_2', 'model_2'])
```

environments:
```
platform: GCP
OS: Ubuntu 16.04.4
GPU: Tesla P100-PCIE-16GB * 4
CUDA version: 9.1
cudnn version: 7.1.2
CPU * 4
Memory: 15GB

python: 3.5.2
tensorflow: 1.7.0
Keras: 2.1.5
```
Before running, I patched:
```
diff --git a/gpufmkmgr/gpufmkmgr.py b/gpufmkmgr/gpufmkmgr.py
index 9f4136b..fe8e9c9 100644
--- a/gpufmkmgr/gpufmkmgr.py
+++ b/gpufmkmgr/gpufmkmgr.py
@@ -186,7 +186,7 @@ def getDeviceIdxsEqualModel(idx):

     for i in range(0, nvmlDeviceGetCount() ):
         if nvmlDeviceGetName(nvmlDeviceGetHandleByIndex(i)).decode() == idx_name:
-            result.append (idx)
+            result.append (i)

     nvmlShutdown()
     return result
```

**Comment by iperov** [comment]
check last commit

**Comment by HelpSeeker** [comment]
@iperov 
I can't confirm it for multiple GPUs, but all steps work fine on Fedora 27, with the exception of the preview during training. I had to manually specify the path to a truetype font file in image_utils.py for the window to pop up. However I'm not sure if that's a Linux, Fedora or just a me problem.

**Comment by iperov** [comment]
what exception in preview?
is there no cour.ttf font in fedora ?

**Comment by iperov** [comment]
also in last commit:
```
if font is None:
        try:
            font = localization.get_default_ttf_font_name()
        except:
            font = ImageFont.load_default()
```

**Comment by iperov** [comment]
hmm this is a bug

**Comment by iperov** [comment]
check last commit

```
    try:
        pil_font = get_pil_font( localization.get_default_ttf_font_name() , size)
    except:
        pil_font = ImageFont.load_default()
```

**Comment by HelpSeeker** [comment]
Works perfectly now. Thanks!

**Comment by HelpSeeker** [comment]
Works perfectly now. Thanks!

**Comment by iperov** [comment]
can you show screenshot of default font in your preview?

**Comment by HelpSeeker** [comment]
![training preview_009](https://user-images.githubusercontent.com/36918959/39014387-8330f018-441a-11e8-8725-b94a6b84b8bd.png)

**Comment by iperov** [comment]
Ok.

What you did with loss ??

**Comment by iperov** [comment]
@shun115 hello, is multi_gpu fixed ?

**Comment by HelpSeeker** [comment]
I played around with the batch size. I started with 16, then switched to 8. The single spike in the first third is batch size 1 and the long stretch in the second half is batch size 2. The last bit is 16 again.

**Comment by iperov** [comment]
ah yes. Batch size affects highest and lowest loss. Cant understand why.

**Comment by iperov** [comment]
And batch-size can be set to 0 - auto.

**Comment by HelpSeeker** [comment]
Yeah, but the auto setting is a bit too low for my taste. I use the SIAEF128 model with a GTX 1070 (8GB VRAM) and it defaults to batch size 2, even though I have ~1 epoch/second with batch size 16.

**Comment by iperov** [comment]
so you confirm that SIAEF128 works on 8GB with 16 batch without problems ?

**Comment by HelpSeeker** [comment]
I used it for the first ~12000 epochs and it didn't throw any errors.

I also tested higher batch sizes. At 64 it starts to throw OOM errors, but they don't prevent training, only slow it down (~5 seconds/epoch; didn't test it for a long period of time though). The training fails once I try batch size 128.

**Comment by shun115** [comment]
@iperov Thanks.
I will check.

**Comment by shun115** [comment]
@iperov I run same command and occurs same error.
```
Error: ('The name "model_2" is used 2 times in the model. All layer names should be unique. Layer names: ', ['input_1', 'input_2', 'lambda_1', 'lambda_2', 'lambda_3', 'lambda_4', 'lambda_5', 'lambda_6', 'lambda_7', 'lambda_8', 'model_6', 'model_2', 'model_2'])
Traceback (most recent call last):
  File "/home/deployer/OpenDeepFaceSwap/mainscripts/Trainer.py", line 41, in trainerThread
    **in_options)
  File "/home/deployer/OpenDeepFaceSwap/models/ModelBase.py", line 115, in __init__
    self.onInitialize(**in_options)
  File "/home/deployer/OpenDeepFaceSwap/models/Model_IAEF128/Model.py", line 59, in onInitialize
    self.autoencoder_src, self.autoencoder_dst = self.to_multi_gpu_model_if_possible ( [self.autoencoder_src, self.autoencoder_dst] )
  File "/home/deployer/OpenDeepFaceSwap/models/ModelBase.py", line 203, in to_multi_gpu_model_if_possible
    return [ self.keras.utils.multi_gpu_model( model, self.gpu_idxs ) for model in models_list ]
  File "/home/deployer/OpenDeepFaceSwap/models/ModelBase.py", line 203, in <listcomp>
    return [ self.keras.utils.multi_gpu_model( model, self.gpu_idxs ) for model in models_list ]
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/utils/multi_gpu_utils.py", line 189, in multi_gpu_model
    return Model(model.inputs, merged)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/deployer/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 4204, in device
    yield
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/utils/multi_gpu_utils.py", line 189, in multi_gpu_model
    return Model(model.inputs, merged)
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/deployer/.local/lib/python3.5/site-packages/keras/engine/topology.py", line 1829, in __init__
    'Layer names: ', all_names)
RuntimeError: ('The name "model_2" is used 2 times in the model. All layer names should be unique. Layer names: ', ['input_1', 'input_2', 'lambda_1', 'lambda_2', 'lambda_3', 'lambda_4', 'lambda_5', 'lambda_6', 'lambda_7', 'lambda_8', 'model_6', 'model_2', 'model_2'])
```

FYI:
https://stackoverflow.com/questions/49712244/training-gans-on-gpus-with-keras-all-layer-names-should-be-unique-for-discrimin
https://gist.github.com/BAXTER001/5b2bb9e65b587f893298f09102436ca1

**Comment by iperov** [comment]
@shun115 fixed

**Comment by shun115** [comment]
@iperov Thank you.
Successfully trainning with multi-gpu.
