### ISSUE TITLE
Extraction fails for large number of files "OSError: [Errno 24] Too many open files"

### ISSUE THREAD

**Issue by badluckwiththinking** [iperov/OpenDeepFaceSwap#6]
Extraction fails on second pass due to too many open files error. Error just after 1000th file.

```
$ python main.py extract --input-dir input_folder --output-dir output_folder --detector dlib```

Running extractor.

Performing 1st pass...
Running extract on GeForce GTX 1060 6GB.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1461/1461 [03:14<00:00,  7.54it/s]
Performing 2nd pass...
/home/fake/miniconda3/envs/df/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-04-19 22:47:03.007409: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-19 22:47:03.007726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.24GiB
2018-04-19 22:47:03.007742: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-04-19 22:47:03.164417: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-19 22:47:03.164440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-04-19 22:47:03.164445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-04-19 22:47:03.164577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5005 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/fake/miniconda3/envs/df/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1349: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Running extract on GeForce GTX 1060 6GB.
69%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                  | 1007/1461 [00:51<00:22, 20.26it/s]
Failed to extract /home/fakes/Desktop/input_folder/qXwdbJY-1-106.jpg, reason: [Errno 24] Too many open files. 
Traceback (most recent call last):
  File "/home/fake/Documents/OpenDeepFaceSwap/mainscripts/Extractor.py", line 50, in extract_pass_process
    landmarks = e.extract_from_bgr (image, rects)
  File "/home/fake/Documents/OpenDeepFaceSwap/facelib/LandmarksExtractor.py", line 126, in extract_from_bgr
    with std_utils.suppress_stdout_stderr():
  File "/home/fake/Documents/OpenDeepFaceSwap/utils/std_utils.py", line 11, in __enter__
OSError: [Errno 24] Too many open files

```

## Other relevant information
- Ubuntu 16.04
- Python 3.6.5
- Cuda 9.0
- CuDNN 7.0

**Comment by iperov** [comment]
you using last commit?

**Comment by Kirin-kun** [comment]
This program has not been tested under Linux. I doubt @iperov will take time to test it with Linux.

But 1461 files? That's not "large". I extracted around 5000 files without a hitch under Windows. 

But I think I know what the problem is.  In Linux, there are hard and soft limits on file descriptors. A hard limit cannot be changed by the user once it is set. Hard limits can only be changed by root user. A soft limit, however, can be changed by the user but cannot exceed the hard limit i.e. It can have minimum 0 value and maximum value as equal to "hard limit".

I think your limit, as a user, is set at default 1024.

There's extensive discussion here: https://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user about this.

**Comment by iperov** [comment]
I had same error with descriptors on WIndows, but only when it reaches ~13k, and then I fixed this bug.

**Comment by badluckwiththinking** [comment]
updating to latest has fixed, thanks!
