### ISSUE TITLE
Core dump error

### ISSUE THREAD

**Issue by shun115** [iperov/OpenDeepFaceSwap#7]
Hi Iperov,

I train on terminal(without GUI, `Ubuntu 16.04.4`).
And error occurs:
```
===== Model summary =====
== Model name: IAEF128
==
== Current epoch: 0
==
== Options:
== |== batch_size : 32
== |== multi_gpu : False
== |== created_vram_gb : 15.8992919921875
== Running on:
== |== [0 : Tesla P100-PCIE-16GB]
=========================
Saving...
Starting. Press "Enter" to stop training and save model.
: cannot connect to X server 0.68309 loss_dst: 0.68305
2018-04-20 06:50:05.135660: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_DEINITIALIZED
2018-04-20 06:50:05.135796: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
Aborted (core dumped)
```

After patched this, I can start trainning.
```
diff --git a/utils/image_utils.py b/utils/image_utils.py
index 15728d8..64b9ba8 100644
--- a/utils/image_utils.py
+++ b/utils/image_utils.py
@@ -62,10 +62,10 @@ def get_text_image( shape, text, color=(1,1,1), border=0.2, font=None):

     size = shape[1]

-    try:
-        pil_font = get_pil_font( localization.get_default_ttf_font_name() , size)
-    except:
-        pil_font = ImageFont.load_default()
+    #try:
+    #    pil_font = get_pil_font( localization.get_default_ttf_font_name() , size)
+    #except:
+    #    pil_font = ImageFont.load_default()

     text_width, text_height = pil_font.getsize(text)
```

**Comment by iperov** [comment]
but if you comment `pil_font` then access to it will cause exception

**Comment by iperov** [comment]
can you show full code

**Comment by iperov** [comment]
try this

```
def get_text_image( shape, text, color=(1,1,1), border=0.2, font=None):
    try:
        def get_pil_font (font, size):
            global pil_fonts
            font_str_id = '%s_%d' % (font, size)
            if font_str_id not in pil_fonts.keys():
                pil_fonts[font_str_id] = ImageFont.truetype(font + ".ttf", size=size, encoding="unic")
            pil_font = pil_fonts[font_str_id]
            return pil_font    

        size = shape[1]
        
        try:
            pil_font = get_pil_font( localization.get_default_ttf_font_name() , size)
        except:
            pil_font = ImageFont.load_default()
        
        text_width, text_height = pil_font.getsize(text)

        canvas = Image.new('RGB', shape[0:2], (0,0,0) )

        draw = ImageDraw.Draw(canvas)
        offset = ( 0, 0) #int(min(shape[0],shape[1])*border)
        draw.text(offset, text, font=pil_font, fill=tuple((np.array(color)*255).astype(np.int)) )
        
        result = np.asarray(canvas) / 255
        if shape[2] != 3:        
            result = np.concatenate ( (result, np.ones ( (shape[1],) + (shape[0],) + (shape[2]-3,)) ), axis=2 )

        return result
    except:    
        return np.zeros ( shape, dtype=np.float32 )
```

**Comment by iperov** [comment]
check last commit

**Comment by shun115** [comment]
@iperov Thank you for your reply.
> but if you comment pil_font then access to it will cause exception

Yes, exception raised. But training process is started.
```
Traceback (most recent call last):66 loss_dst: 0.68102
  File "main.py", line 115, in <module>
    arguments.func(arguments)
  File "main.py", line 65, in process_train
    multi_gpu          = arguments.multi_gpu
  File "/home/deployer/OpenDeepFaceSwap/mainscripts/Trainer.py", line 287, in main
    previewThread (input_queue, output_queue)
  File "/home/deployer/OpenDeepFaceSwap/mainscripts/Trainer.py", line 187, in previewThread
    head[t:b, 0:w] += image_utils.get_text_image (  (w,head_line_height,c) , head_lines[i], color=head_text_color )
  File "/home/deployer/OpenDeepFaceSwap/utils/image_utils.py", line 70, in get_text_image
    text_width, text_height = pil_font.getsize(text)
NameError: name 'pil_font' is not defined
```

> check last commit

Thank you.
I run latest code without GUI.
But still error occurs:
```
Starting. Press "Enter" to stop training and save model.
: cannot connect to X server 0.66857 loss_dst: 0.68461
2018-04-20 08:55:42.188806: E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_DEINITIALIZED
2018-04-20 08:55:42.188918: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:203] Unexpected Event status: 1
Aborted (core dumped)
```

**Comment by iperov** [comment]
I have no command line server without gui to test it.

**Comment by iperov** [comment]
if you can research problem and fix it- you are welcome

**Comment by bonlime** [comment]
@iperov 
I had the same "cannot connect to X server" error. It can be easily fixed by deactivating Preview thread in Trainer. 
Maybe you can add --no-gui parameter, for users who work in terminal only systems

**Comment by iperov** [comment]
No I cannot, there is no control of training in console mode.

**Comment by bonlime** [comment]
жаль(
it looks like the only possible way to use it right now, is to train until fixed epoch
will make PL when fix it

**Comment by iperov** [comment]
ok may be later I will add option. Not now.
